Modules/Country/Http/routes.php
<?php

Route::group(['middleware' => ['web','admin'], 'as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Modules\Country\Http\Controllers'], function () 
{
    /*
     * For DataTables
     */
    Route::post('country/get', 'CountryTableController')->name('country.get');
    /*
     * User CRUD
     */
    Route::resource('country', 'CountryController');
});

Modules/Country/Entities/Country.php
<?php

namespace Modules\Country\Entities;
use Modules\State\Entities\State;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use App\Enums\Table;

class Country extends Model
{
    use SoftDeletes;
    /**
    * The database table used by the model.
    *
    * @var string
    */
    protected $table = Table::COUNTRY;

    protected $fillable = ["id","name","country_code"];
    public function state()
    {
        return $this->hasMany(State::class);
    }
    /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
        if (auth()->user()->can('view country')) {
            return '<a href="'.route('admin.country.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
        }
        return '';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        if (auth()->user()->can('edit country')) {
            return '<a href="'.route('admin.country.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
        }
        return '';
    }

    /**
    * @return string
    */
    public function getDeleteButtonAttribute()
    {
        if (auth()->user()->can('delete country')) {
            return '<a href="'.route('admin.country.destroy', $this).'" data-method="delete"
                 data-trans-button-cancel="'.__('buttons.general.cancel').'"
                 data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                 data-trans-title="'.__('strings.backend.general.are_you_sure').'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.delete').'" class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
        }

        return '';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        return $this->getShowButtonAttribute().$this->getEditButtonAttribute().$this->getDeleteButtonAttribute();
    }
}

Modules/Country/Http/Controllers/CountryController.php
<?php

namespace Modules\Country\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\State\Repositories\StateRepository;
use Modules\Country\Entities\Country;
use Modules\Country\Http\Requests\ManageCountryRequest;
use Modules\Country\Http\Requests\CreateCountryRequest;
use Modules\Country\Http\Requests\UpdateCountryRequest;
use Modules\Country\Http\Requests\ShowCountryRequest;
use Modules\Country\Repositories\CountryRepository;

class CountryController extends Controller
{
    /**
        * @var CountryRepository
        * @var CategoryRepository
        */
    protected $country;
    protected $state;

    /**
     * @param CountryRepository $country
     */
    public function __construct(CountryRepository $country, StateRepository $state)
    {
        $this->country = $country;
        $this->state = $state;
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('country::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('country::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(CreateCountryRequest $request)
    {
        $this->country->create($request->except('_token', '_method'));
        return redirect()->route('admin.country.index')->withFlashSuccess(trans('country::alerts.backend.country.created'));
    }

    /**
     * @param Country              $country
     * @param ManageCountryRequest $request
     *
     * @return mixed
     */
    public function edit(Country $country, ManageCountryRequest $request)
    {
        return view('country::edit')
            ->withCountry($country);
    }

    /**
     * @param Country              $country
     * @param UpdateCountryRequest $request
     *
     * @return mixed
     */
    public function update(Country $country, UpdateCountryRequest $request)
    {
        $this->country->updateById($country->id, $request->except('_token', '_method'));

        return redirect()->route('admin.country.index')->withFlashSuccess(trans('country::alerts.backend.country.updated'));
    }

    /**
     * @param Country              $country
     * @param ManageCountryRequest $request
     *
     * @return mixed
     */
    public function show(Country $country, ShowCountryRequest $request)
    {
        return view('country::show')->withCountry($country);
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy(Country $country)
    {
        if(optional($country->state)->count()) 
        {
            return redirect()->route('admin.country.index')->withFlashDanger(trans('country::alerts.backend.country.not_deleted'));
        }
        $this->country->deleteById($country->id);

        return redirect()->route('admin.country.index')->withFlashSuccess(trans('country::alerts.backend.country.deleted'));
    }
}

Modules/Country/Http/Controllers/CountryTableController.php
<?php

namespace Modules\Country\Http\Controllers;

use Illuminate\Routing\Controller;
use DataTables;
use Modules\Country\Repositories\CountryRepository;
use Modules\Country\Http\Requests\ManageCountryRequest;

class CountryTableController extends Controller
{
    /**
     * @var CountryRepository
     */
    protected $country;

    /**
     * @param CountryRepository $country
     */
    public function __construct(CountryRepository $country)
    {
        $this->country = $country;
    }

    /**
     * @param ManageCountryRequest $request
     *
     * @return mixed
     */
    public function __invoke(ManageCountryRequest $request)
    {
        return DataTables::of($this->country->getForDataTable())
            ->addColumn('actions', function ($country) {
                return $country->action_buttons;
            })
            ->rawColumns(['actions'])
            ->make(true);
    }
}

Modules/Country/Resources/views/create.blade.php
@extends ('backend.layouts.app')

@section ('title', __('country::labels.backend.country.management') . ' | ' . __('country::labels.backend.country.create'))

@section('breadcrumb-links')
    @include('country::includes.breadcrumb-links')
@endsection

@push('after-styles')

@endpush

@section('content')
{{ html()->form('POST', route('admin.country.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('country::labels.backend.country.management') }}
                        <small class="text-muted">{{ __('country::labels.backend.country.create') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">

                    <div class="form-group row">
                    {{ html()->label(__('country::labels.backend.country.table.name').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('name') }}

                        <div class="col-md-10">
                            {{ html()->text('name')
                                ->class('form-control')
                                ->placeholder(__('country::labels.backend.country.table.name'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('country::labels.backend.country.table.country_code').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('country_code') }}

                        <div class="col-md-10">
                            {{ html()->text('country_code')
                                ->class('form-control')
                                ->placeholder(__('country::labels.backend.country.table.country_code'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.country.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')

<script>


</script>
@endpush

Modules/Country/Resources/views/edit.blade.php
@extends ('backend.layouts.app')

@section ('title', __('country::labels.backend.country.management') . ' | ' . __('country::labels.backend.country.edit'))

@section('breadcrumb-links')
    @include('country::includes.breadcrumb-links')
@endsection

@push('after-styles')

@endpush

@section('content')
{{ html()->modelForm($country, 'PATCH', route('admin.country.update', $country->id))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('country::labels.backend.country.management') }}
                        <small class="text-muted">{{ __('country::labels.backend.country.edit') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">

                    <div class="form-group row">
                    {{ html()->label(__('country::labels.backend.country.table.name'))->class('col-md-2 form-control-label')->for('name') }}

                        <div class="col-md-10">
                            {{ html()->text('name')
                                ->class('form-control')
                                ->placeholder(__('country::labels.backend.country.table.name'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('country::labels.backend.country.table.country_code'))->class('col-md-2 form-control-label')->for('country_code') }}

                        <div class="col-md-10">
                            {{ html()->text('country_code')
                                ->class('form-control')
                                ->placeholder(__('country::labels.backend.country.table.country_code'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.country.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.update')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')

<script>


</script>
@endpush

Modules/Country/Resources/views/index.blade.php
@extends ('backend.layouts.app')

@section ('title', app_name() . ' | ' . __('country::labels.backend.country.management'))

@section('breadcrumb-links')
    @include('country::includes.breadcrumb-links')
@endsection

@push('after-styles')
    {{ style("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css") }}
@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('country::labels.backend.country.management') }} <small class="text-muted">{{ __('country::labels.backend.country.list') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('country::includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table id="country-table" class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('country::labels.backend.country.table.id') }}</th>
                            <th>{{ __('country::labels.backend.country.table.name') }}</th>
                            <th>{{ __('country::labels.backend.country.table.country_code') }}</th>
                            <th>{{ __('country::labels.backend.country.table.last_updated') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

@push('after-scripts')
    {{ script("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js") }}
    {{ script("js/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#country-table').DataTable({
                processing: true,
                language:{processing: "<div class='overlay custom-loader-background' style='font-size:2em;'><i class='fa fa-cog fa-spin custom-loader-color'></i></div>"},
                serverSide: true,
                ajax: {
                    url: '{!! route("admin.country.get") !!}',
                    type: 'post',
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                        else swal(xhr.responseJSON.message);
                    }
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'country_code', name: 'country_code'},
                    {data: 'updated_at', name: 'updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500,
                fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    load_plugins();
                }
            });
        });
    </script>
@endpush

Modules/Country/Resources/views/show.blade.php
@extends ('backend.layouts.app')

@section ('title', __('country::labels.backend.country.management'))

@section('breadcrumb-links')
    @include('country::includes.breadcrumb-links')
@endsection

@push('after-styles')

@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('country::labels.backend.country.management') }}
                    <small class="text-muted">{{ __('country::labels.backend.country.show') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>{{ __('country::labels.backend.country.table.name') }}</th>
                                <td>{{ $country->name }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('country::labels.backend.country.table.country_code') }}</th>
                                <td>{{ $country->country_code }}</td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->

    <div class="card-footer">
        <div class="row">
            <div class="col">
                <small class="float-right text-muted">
                    <strong>{{ __('country::labels.backend.country.table.created') }}:</strong> {{ $country->updated_at->timezone(get_user_timezone()) }} ({{ $country->created_at->diffForHumans() }}),
                    <strong>{{ __('country::labels.backend.country.table.last_updated') }}:</strong> {{ $country->created_at->timezone(get_user_timezone()) }} ({{ $country->updated_at->diffForHumans() }})
                </small>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-footer-->
</div><!--card-->
@endsection

@push('after-scripts')

<script>


</script>
@endpush