Modules/Host/Http/routes.php
<?php

Route::group(['middleware' => ['web','admin'], 'as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Modules\Host\Http\Controllers'], function()
{
    		/*
             * For DataTables
             */
            Route::post('host/get', 'HostTableController')->name('host.get');

            /*
             * User CRUD
             */
            Route::resource('host', 'HostController');

            Route::get('host/inactive/{host_id}', 'HostController@inActive')->name('host.inactive');
            Route::get('host/active/{host_id}', 'HostController@active')->name('host.active');


});

Modules/Host/Entities/Host.php
<?php

namespace Modules\Host\Entities;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Modules\State\Entities\State;
use Modules\City\Entities\City;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use Modules\Host\Entities\HostUser;
use Modules\Township\Entities\Township;
use Modules\HostCategory\Entities\HostCategory;
use App\Models\Auth\User;

class Host extends Model
{
    use SoftDeletes;
	 /**
     * The database table used by the model.
     *
     * @var string
     */
    use Sluggable;
    use SluggableScopeHelpers;

    protected $table = 'host';
    protected $primaryKey = 'host_id';

    protected $fillable = ['host_id','host_name','host_mmname', 'slug','host_category_id','description','mm_description','host_qrcode','host_mobileno','host_logo','latitude','longitude','address_detail','state_id','city_id','township_id','sick_status','trip_status','is_active'];


    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'host_name'
            ]
        ];
    }

    public function township()
    {
        return $this->hasOne(Township::class, 'id', 'township_id');
    }

    public function state()
    {
        return $this->hasOne(State::class, 'id', 'state_id');
    }

    public function city()
    {
        return $this->hasOne(City::class, 'id', 'city_id');
    }

    public function host_category()
    {
        return $this->hasOne(HostCategory::class, 'host_category_id', 'host_category_id');
    }

    public function host_user()
    {
        return $this->hasMany(HostUser::class, 'host_id');
    }


       /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
    	if(auth()->user()->can('view host')){
        	return '<a href="'.route('admin.host.show', $this->host_id).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
        }
       	return '';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
    	if(auth()->user()->can('edit host')){
        	return '<a href="'.route('admin.host.edit', $this->host_id).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
        }
       	return '';
    }

     /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        if (auth()->user()->can('delete host')) {
            return '<a href="'.route('admin.host.destroy', $this->host_id).'" data-method="delete"
                 data-trans-button-cancel="'.__('buttons.general.cancel').'"
                 data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                 data-trans-title="'.__('strings.backend.general.are_you_sure').'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.delete').'" class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
        }

        return '';
    }

    public function getStatusLabelAttribute()
    {
        if ($this->is_active == 1) {
            return '<span class="badge badge-success">active</span>';
        }

        return "<span class='badge badge-danger'>".__('labels.general.inactive').'</span>';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
            return $this->getShowButtonAttribute().$this->getEditButtonAttribute();
    }
}

Modules/Host/Resources/views/create.blade.php
@extends ('backend.layouts.app')

@section ('title', __('host::labels.backend.host.management') . ' | ' . __('host::labels.backend.host.create'))

@section('breadcrumb-links')
    @include('host::includes.breadcrumb-links')
@endsection

@push('after-styles')

@endpush

@section('content')
{{ html()->form('POST', route('admin.host.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('host::labels.backend.host.management') }}
                        <small class="text-muted">{{ __('host::labels.backend.host.create') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">

                    <div class="form-group row">
                    {{ html()->label(__('host::labels.backend.host.table.name'))->class('col-md-2 form-control-label')->for('name') }}

                        <div class="col-md-10">
                            {{ html()->text('name')
                                ->class('form-control')
                                ->placeholder(__('host::labels.backend.host.table.name'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('host::labels.backend.host.table.description'))->class('col-md-2 form-control-label')->for('description') }}

                        <div class="col-md-10">
                            {{ html()->textarea('description')
                                ->class('form-control')
                                ->placeholder(__('host::labels.backend.host.table.description'))
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.host.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')

<script>


</script>
@endpush

Modules/Host/Resources/views/index.blade.php
@extends ('backend.layouts.app')

@section ('title', app_name() . ' | ' . __('host::labels.backend.host.management'))

@section('breadcrumb-links')
    @include('host::includes.breadcrumb-links')
@endsection

@push('after-styles')
    {{ style("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css") }}
@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('host::labels.backend.host.management') }} <small class="text-muted">{{ __('host::labels.backend.host.list') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('host::includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table id="host-table" class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('host::labels.backend.host.table.id') }}</th>
                            <th>{{ __('host::labels.backend.host.table.name') }}</th>
                            <th>{{ __('host::labels.backend.host.table.mm_name') }}</th>
                            <th>{{ __('host::labels.backend.host.table.mobile') }}</th>
                            <th>{{ __('host::labels.backend.host.table.host_category') }}</th>
                            <th>{{ __('host::labels.backend.host.table.township') }}</th>
                            <th>{{ __('host::labels.backend.host.table.city') }}</th>
                            <th>{{ __('host::labels.backend.host.table.description') }}</th>
                            <th>{{ __('host::labels.backend.host.table.qr') }}</th>
                            <th>{{ __('host::labels.backend.host.table.status') }}</th>
                            <th>{{ __('host::labels.backend.host.table.last_updated') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

@push('after-scripts')
    {{ script("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js") }}
    {{ script("js/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#host-table').DataTable({
                serverSide: true,
                ajax: {
                    url: '{!! route("admin.host.get") !!}',
                    type: 'post',
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                        else swal(xhr.responseJSON.message);
                    }
                },
                columns: [
                    {data: 'host_id', name: 'host_id'},
                    {data: 'host_name', name: 'host_name'},
                    {data: 'host_mmname', name: 'host_mmname'},
                    {data: 'host_mobileno', name: 'host_mobileno'},
                    {data: 'host_category_id', name: 'host_category_id'},
                    {data: 'township_id', name: 'township_id'},
                    {data: 'city_id', name: 'city_id'},
                    {data: 'description', name: 'description'},
                    {data: 'host_qrcode', name: 'host_qrcode'},
                    {data: 'status', name: 'status'},
                    {data: 'updated_at', name: 'updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500,
                fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    load_plugins();
                }
            });
        });
    </script>
@endpush

Modules/Host/Resources/views/show.blade.php
@extends ('backend.layouts.app')

@section ('title', __('host::labels.backend.host.management'))

@section('breadcrumb-links')
    @include('host::includes.breadcrumb-links')
@endsection

@push('after-styles')

@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('host::labels.backend.host.management') }}
                    <small class="text-muted">{{ __('host::labels.backend.host.show') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.name') }}</th>
                                <td>{{ $host->host_name }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.mm_name') }}</th>
                                <td>{{ $host->host_mmname }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.slug') }}</th>
                                <td>{{ $host->slug }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.mobile') }}</th>
                                <td>{{ $host->host_mobileno }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.host_category') }}</th>
                                <td>{{ $host->host_category->host_category_name }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.description') }}</th>
                                <td>{{ $host->description }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.mm_description') }}</th>
                                <td>{{ $host->mm_description }}</td>
                            </tr>
                            
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.latitude') }}</th>
                                <td>{{ $host->latitude }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.longitude') }}</th>
                                <td>{{ $host->longitude }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.address') }}</th>
                                <td>{{ $host->address_detail }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.state') }}</th>
                                <td>{{ $host->state->name }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.city') }}</th>
                                <td>{{ $host->city->name }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.township') }}</th>
                                <td>{{ $host->township->name }}</td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.sick_status') }}</th>
                                <td>
                                    @if($host->sick_status == 1)
                                        Yes
                                    @else
                                        No
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.trip_status') }}</th>
                                <td>
                                    @if($host->trip_status == 1)
                                        Yes
                                    @else
                                        No
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.qr') }}</th>
                                <td><img src="{{ $host->host_qrcode }}" width="100" height="100"></td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.logo') }}</th>
                                <td><img src="{{ url('uploads/'.$host->host_logo) }}" width="100" height="100"></td>
                            </tr>
                            <tr>
                                <th>{{ __('host::labels.backend.host.table.status') }}</th>
                                <td>{!! $host->status_label !!}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->

    <div class="card-footer">
        <div class="row">
            <div class="col">
                <small class="float-right text-muted">
                    <strong>{{ __('host::labels.backend.host.table.created') }}:</strong> {{ $host->updated_at->timezone(get_user_timezone()) }} ({{ $host->created_at->diffForHumans() }}),
                    <strong>{{ __('host::labels.backend.host.table.last_updated') }}:</strong> {{ $host->created_at->timezone(get_user_timezone()) }} ({{ $host->updated_at->diffForHumans() }})
                </small>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-footer-->
</div><!--card-->
@endsection

@push('after-scripts')

<script>


</script>
@endpush