Modules/Route/Http/routes.php
<?php

Route::group(['middleware' => ['web','admin'], 'as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Modules\Route\Http\Controllers'], function()
{
    /*
        * For DataTables
        */
    Route::post('route/get', 'RouteTableController')->name('route.get');
    /*
        * User CRUD
        */
    Route::resource('route', 'RouteController');
});

Modules/Route/Entities/Route.php
<?php

namespace Modules\Route\Entities;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use App\Enums\Table;
use Modules\City\Entities\City;
use Modules\SubRoute\Entities\SubRoute;

class Route extends Model
{
    use SoftDeletes;
	 /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = Table::ROUTE;

    protected $fillable = ["id", "from_city_id", "to_city_id", "is_active"];

    public function subroute()
    {
        return $this->belongsToMany(SubRoute::class, Table::PIVOT_ROUTE, 'route_id', 'sub_route_id');
    }
    
    public function toCity()
    {
        return $this->belongsTo(City::class, 'to_city_id');
    }
    
    public function fromCity()
    {
        return $this->belongsTo(City::class, 'from_city_id');
    }
       /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
    	if(auth()->user()->can('view route')){
        	return '<a href="'.route('admin.route.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
        }
       	return '';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
    	if(auth()->user()->can('edit route')){
        	return '<a href="'.route('admin.route.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
        }
       	return '';
    }

     /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        if (auth()->user()->can('delete route')) {
            return '<a href="'.route('admin.route.destroy', $this).'" data-method="delete"
                 data-trans-button-cancel="'.__('buttons.general.cancel').'"
                 data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                 data-trans-title="'.__('strings.backend.general.are_you_sure').'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.delete').'" class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
        }

        return '';
    }
    public function getStatusLabelAttribute()
    {
        if ($this->is_active == 1) {
            return '<span class="badge badge-success">active</span>';
        }

        return "<span class='badge badge-danger'>".__('labels.general.inactive').'</span>';
    }
    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
            return $this->getShowButtonAttribute().$this->getEditButtonAttribute().$this->getDeleteButtonAttribute();
    }
}

Modules/Route/Http/Controllers/RouteController.php
<?php

namespace Modules\Route\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

use Modules\Route\Entities\Route;
use Modules\Route\Http\Requests\ManageRouteRequest;
use Modules\Route\Http\Requests\CreateRouteRequest;
use Modules\Route\Http\Requests\UpdateRouteRequest;
use Modules\Route\Http\Requests\ShowRouteRequest;
use Modules\Route\Repositories\RouteRepository;
use Modules\City\Repositories\CityRepository;

class RouteController extends Controller
{
 /**
     * @var RouteRepository
     * @var CategoryRepository
     */
    protected $route;
    protected $city;
    /**
     * @param RouteRepository $route
     */
    public function __construct(RouteRepository $route, CityRepository $city)
    {
        $this->route = $route;
        $this->city = $city;
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('route::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $cities = $this->city->getAll('id','asc');
        return view('route::create',compact('cities'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(CreateRouteRequest $request)
    {
        $this->route->create($request->except('_token','_method'));
        return redirect()->route('admin.route.index')->withFlashSuccess(trans('route::alerts.backend.route.created'));
    }

    /**
     * @param Route              $route
     * @param ManageRouteRequest $request
     *
     * @return mixed
     */
    public function edit(Route $route, ManageRouteRequest $request)
    {
        $cities = $this->city->getAll('id','asc');
        return view('route::edit',compact('cities'))
            ->withRoute($route);
    }

    /**
     * @param Route              $route
     * @param UpdateRouteRequest $request
     *
     * @return mixed
     */
    public function update(Route $route, UpdateRouteRequest $request)
    {
        $request['is_active'] = $request->is_active ? $request->is_active : 0;
        $this->route->updateById($route->id,$request->except('_token','_method'));

        return redirect()->route('admin.route.index')->withFlashSuccess(trans('route::alerts.backend.route.updated'));
    }

    /**
     * @param Route              $route
     * @param ManageRouteRequest $request
     *
     * @return mixed
     */
    public function show(Route $route, ShowRouteRequest $request)
    {
        return view('route::show')->withRoute($route);
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy(Route $route)
    {
        if(optional($route->subroute)->count())
        {
            return redirect()->route('admin.route.index')->withFlashDanger(trans('route::alerts.backend.route.not_deleted'));
        }
        $this->route->deleteById($route->id);

        return redirect()->route('admin.route.index')->withFlashSuccess(trans('route::alerts.backend.route.deleted'));
    }
}

Modules/Route/Http/Controllers/RouteTableController.php
<?php

namespace Modules\Route\Http\Controllers;

use Illuminate\Routing\Controller;
use DataTables;
use Modules\Route\Repositories\RouteRepository;
use Modules\Route\Http\Requests\ManageRouteRequest;

class RouteTableController extends Controller
{
    /**
     * @var RouteRepository
     */
    protected $route;

    /**
     * @param RouteRepository $route
     */
    public function __construct(RouteRepository $route)
    {
        $this->route = $route;
    }

    /**
     * @param ManageRouteRequest $request
     *
     * @return mixed
     */
    public function __invoke(ManageRouteRequest $request)
    {
        return DataTables::of($this->route->getForDataTable())
            ->addColumn('actions', function ($route) {
                return $route->action_buttons;
            }) 
            ->addColumn('to_city_id', function ($route) {
                return $route->toCity->name;
            })
            ->addColumn('from_city_id', function ($route) {
                return $route->fromCity->name;
            })
            ->addColumn('status', function ($route) {
                return $route->status_label;
            })
        ->rawColumns(['actions','to_city_id', 'from_city_id','status'])
            ->make(true);
    }
}

Modules/Route/Resources/views/create.blade.php
@extends ('backend.layouts.app')

@section ('title', __('route::labels.backend.route.management') . ' | ' . __('route::labels.backend.route.create'))

@section('breadcrumb-links')
    @include('route::includes.breadcrumb-links')
@endsection

@push('after-styles')
{{ style('assets/plugins/select2/css/select2.min.css') }}
{{ style('assets/plugins/select2/css/select2-bootstrap.min.css') }}
@endpush

@section('content')
{{ html()->form('POST', route('admin.route.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('route::labels.backend.route.management') }}
                        <small class="text-muted">{{ __('route::labels.backend.route.create') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">

                    
                    <div class="form-group row">
                    {{ html()->label(__('route::labels.backend.route.table.from_city').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="from_city_id" id="" class="form-control select2">
                                @foreach($cities as $city)
                                    <option value="{{$city->id}}">{{ $city->name}}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('route::labels.backend.route.table.to_city').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="to_city_id" id="" class="form-control select2">
                                @foreach($cities as $city)
                                    <option value="{{$city->id}}">{{ $city->name }}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('route::labels.backend.route.table.active'))->class('col-md-2 form-control-label')->for('active') }}

                        <div class="col-md-10">
                            <label class="switch switch-label switch-pill switch-primary">
                                {{ html()->checkbox('is_active', true)->class('switch-input') }}
                                <span class="switch-slider" data-checked="yes" data-unchecked="no"></span>
                            </label>
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.route.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')

{{ script('assets/plugins/select2/js/select2.full.min.js')}}
{{ script("assets/plugins/select2/component/components-select2.js") }}
<script>
    $(function(){

        $(".select").select2({
            placeholder: 'Choose city',
            width: '100%'
        });
    });
</script>

@endpush

Modules/Route/Resources/views/edit.blade.php
@extends ('backend.layouts.app')

@section ('title', __('route::labels.backend.route.management') . ' | ' . __('route::labels.backend.route.edit'))

@section('breadcrumb-links')
    @include('route::includes.breadcrumb-links')
@endsection

@push('after-styles')
{{ style('assets/plugins/select2/css/select2.min.css') }}
{{ style('assets/plugins/select2/css/select2-bootstrap.min.css') }}
@endpush

@section('content')
{{ html()->modelForm($route, 'PATCH', route('admin.route.update', $route->id))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('route::labels.backend.route.management') }}
                        <small class="text-muted">{{ __('route::labels.backend.route.edit') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">
                <div class="form-group row">
                    {{ html()->label(__('route::labels.backend.route.table.to_city'))->class('col-md-2 form-control-label')->for('description') }}
                        <div class="col-md-10">
                                <select name="to_city_id"  class="form-control select2_city">
                                    @foreach($cities as $city)
                                        <option value="{{ $city->id }}" @if($city->id == $route->to_city_id) selected @endif >{{$city->name}}</option>
                                    @endforeach
                                </select>
                        </div><!--col-->   
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('route::labels.backend.route.table.from_city'))->class('col-md-2 form-control-label')->for('description') }}
                        <div class="col-md-10">
                                <select name="from_city_id"  class="form-control select2_city">
                                    @foreach($cities as $city)
                                        <option value="{{ $city->id }}" @if($city->id == $route->from_city_id) selected @endif >{{$city->name}}</option>
                                    @endforeach
                                </select>
                        </div><!--col-->   
                    </div><!--form-group-->
                    <div class="form-group row">
                        {{ html()->label(__('route::labels.backend.route.table.active'))->class('col-md-2 form-control-label')->for('active') }}

                        <div class="col-md-10">
                            <label class="switch switch-label switch-pill switch-primary">
                                @if($route->is_active == 1)
                                    {{ html()->checkbox('is_active', true)->class('switch-input') }}
                                @else
                                    {{ html()->checkbox('is_active', false)->class('switch-input') }}
                                @endif
                                <span class="switch-slider" data-checked="yes" data-unchecked="no"></span>
                            </label>
                        </div><!--col-->
                    </div><!--form-group-->

                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.route.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.update')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')
{{ script('assets/plugins/select2/js/select2.full.min.js')}}
{{ script("assets/plugins/select2/component/components-select2.js") }}
<script>
$(function(){

    $(".select2_city").select2({
        placeholder: 'Choose city',
        width: '100%'
    });
});
</script>
@endpush

Modules/Route/Resources/views/includes/breadcrumb-links.blade.php
<li class="breadcrumb-menu">
    <div class="btn-group" role="group" aria-label="Button group">
        <div class="dropdown">
            <a class="btn dropdown-toggle" href="#" role="button" id="breadcrumb-dropdown-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ __('route::menus.backend.route.main') }}</a>

            <div class="dropdown-menu" aria-labelledby="breadcrumb-dropdown-1">
                <a class="dropdown-item" href="{{ route('admin.route.index') }}">{{ __('route::menus.backend.route.all') }}</a>
                @can('create route')
                <a class="dropdown-item" href="{{ route('admin.route.create') }}">{{ __('route::menus.backend.route.create') }}</a>
                @endcan
            </div>
        </div><!--dropdown-->

        <!--<a class="btn" href="#">Static Link</a>-->
    </div><!--btn-group-->
</li>

Modules/Route/Resources/views/includes/header-buttons.blade.php
@can('create route')
<div class="btn-toolbar float-right" role="toolbar" aria-label="Toolbar with button groups">
    <a href="{{ route('admin.route.create') }}" class="btn btn-success ml-1" data-toggle="tooltip" title="{{ __('route::menus.backend.route.create') }}"><i class="fas fa-plus-circle"></i></a>
</div>
<!--btn-toolbar-->
@endcan

Modules/Route/Resources/views/index.blade.php
@extends ('backend.layouts.app')

@section ('title', app_name() . ' | ' . __('route::labels.backend.route.management'))

@section('breadcrumb-links')
    @include('route::includes.breadcrumb-links')
@endsection

@push('after-styles')
    {{ style("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css") }}
@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('route::labels.backend.route.management') }} <small class="text-muted">{{ __('route::labels.backend.route.list') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('route::includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table id="route-table" class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('route::labels.backend.route.table.id') }}</th>
                            <th>{{ __('route::labels.backend.route.table.from_city') }}</th>
                            <th>{{ __('route::labels.backend.route.table.to_city') }}</th>
                            <th>{{ __('route::labels.backend.route.table.status') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

@push('after-scripts')
    {{ script("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js") }}
    {{ script("js/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#route-table').DataTable({
                serverSide: true,
                ajax: {
                    url: '{!! route("admin.route.get") !!}',
                    type: 'post',
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                        else swal(xhr.responseJSON.message);
                    }
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'from_city_id', name: 'from_city_id'},
                    {data: 'to_city_id', name: 'to_city_id'},
                    {data: 'status', name: 'status'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500,
                fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    load_plugins();
                }
            });
        });
    </script>
@endpush

Modules/Route/Resources/views/show.blade.php
@extends ('backend.layouts.app')

@section ('title', __('route::labels.backend.route.management'))

@section('breadcrumb-links')
    @include('route::includes.breadcrumb-links')
@endsection

@push('after-styles')

@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('route::labels.backend.route.management') }}
                    <small class="text-muted">{{ __('route::labels.backend.route.show') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>{{ __('route::labels.backend.route.table.to_city') }}</th>
                            <td>{{ $route->toCity->name }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('route::labels.backend.route.table.from_city') }}</th>
                            <td>{{ $route->fromCity->name }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('route::labels.backend.route.table.is_active') }}</th>
                            <td>
                                @if($route->is_active == 1)
                                On
                                @else
                                off
                                @endif
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->

    <div class="card-footer">
        <div class="row">
            <div class="col">
                <small class="float-right text-muted">
                    <strong>{{ __('route::labels.backend.route.table.created') }}:</strong> {{ $route->updated_at->timezone(get_user_timezone()) }} ({{ $route->created_at->diffForHumans() }}),
                    <strong>{{ __('route::labels.backend.route.table.last_updated') }}:</strong> {{ $route->created_at->timezone(get_user_timezone()) }} ({{ $route->updated_at->diffForHumans() }})
                </small>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-footer-->
</div><!--card-->
@endsection

@push('after-scripts')

<script>


</script>
@endpush