Modules/SubRoute/Http/routes.php
<?php

Route::group(['middleware' => ['web','admin'], 'as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Modules\SubRoute\Http\Controllers'], function()
{
    /*
        * For DataTables
        */
    Route::post('subroute/get', 'SubRouteTableController')->name('subroute.get');
    /*
        * User CRUD
        */
    Route::resource('subroute', 'SubRouteController');
});

Modules/SubRoute/Resources/views/create.blade.php
@extends ('backend.layouts.app')

@section ('title', __('subroute::labels.backend.subroute.management') . ' | ' . __('subroute::labels.backend.subroute.create'))

@section('breadcrumb-links')
    @include('subroute::includes.breadcrumb-links')
@endsection

@push('after-styles')
{{ style('assets/plugins/select2/css/select2.min.css') }}
{{ style('assets/plugins/select2/css/select2-bootstrap.min.css') }}
@endpush

@section('content')
{{ html()->form('POST', route('admin.subroute.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('subroute::labels.backend.subroute.management') }}
                        <small class="text-muted">{{ __('subroute::labels.backend.subroute.create') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.name'))->class('col-md-2 form-control-label')->for('name') }}

                        <div class="col-md-10">
                            {{ html()->text('name')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.name'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.from_township').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="from_township_id" id="" class="form-control select2">
                                @foreach($townships as $township)
                                    <option value="{{$township->id}}">{{ $township->name}}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('subroute::labels.backend.subroute.table.to_township').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="to_township_id" id="" class="form-control select2">
                                @foreach($townships as $township)
                                    <option value="{{$township->id}}">{{ $township->name }}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.type').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="type" id="type" class="form-control select2">
                                @foreach($types as $key=>$value)
                                    <option value="{{$key}}">{{ $value}}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('subroute::labels.backend.subroute.table.route').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select class="js-example-basic-multiple select2" name="routes[]" multiple="multiple">
                                @foreach($routes as $route)
                                    <option value="{{$route->id}}">{{ $route->fromCity->name }} to {{ $route->toCity->name }}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_height').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('max_height') }}

                        <div class="col-md-10">
                            {{ html()->text('max_height')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_height'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_weight').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('max_weight') }}

                        <div class="col-md-10">
                            {{ html()->text('max_weight')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_weight'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_width').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('max_width') }}

                        <div class="col-md-10">
                            {{ html()->text('max_width')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_width'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_length'))->class('col-md-2 form-control-label')->for('max_length') }}

                        <div class="col-md-10">
                            {{ html()->text('max_length')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_length'))
                                ->attribute('maxlength', 191)
                                 }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.mmk_price').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('mmk_price') }}

                        <div class="col-md-10">
                            {{ html()->text('mmk_price')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.mmk_price'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.usd_price').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('usd_price') }}

                        <div class="col-md-10">
                            {{ html()->text('usd_price')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.usd_price'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.subroute.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')
{{ script('assets/plugins/select2/js/select2.full.min.js')}}
{{ script("assets/plugins/select2/component/components-select2.js") }}
<script>
    $(function(){

        $(".select").select2({
            placeholder: 'Choose city',
            width: '100%'
        });
    });
</script>

@endpush

Modules/SubRoute/Resources/views/edit.blade.php
@extends ('backend.layouts.app')

@section ('title', __('subroute::labels.backend.subroute.management') . ' | ' . __('subroute::labels.backend.subroute.edit'))

@section('breadcrumb-links')
    @include('subroute::includes.breadcrumb-links')
@endsection

@push('after-styles')
{{ style('assets/plugins/select2/css/select2.min.css') }}
{{ style('assets/plugins/select2/css/select2-bootstrap.min.css') }}
@endpush

@section('content')
{{ html()->modelForm($subroute, 'PATCH', route('admin.subroute.update', $subroute->id))->class('form-horizontal')->open() }}
<div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('subroute::labels.backend.subroute.management') }}
                        <small class="text-muted">{{ __('subroute::labels.backend.subroute.create') }}</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.name'))->class('col-md-2 form-control-label')->for('name') }}

                        <div class="col-md-10">
                            {{ html()->text('name')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.name'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.from_township').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="from_township_id" id="" class="form-control select2">
                                @foreach($townships as $township)
                                    <option value="{{$township->id}}" @if($township->id == $subroute->from_township_id) selected @endif>{{ $township->name}}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('subroute::labels.backend.subroute.table.to_township').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="to_township_id" id="" class="form-control select2">
                                @foreach($townships as $township)
                                    <option value="{{$township->id}}" @if($township->id == $subroute->to_township_id) selected @endif >{{ $township->name }}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.type').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select name="type" id="type" class="form-control select2">
                                @foreach($types as $key=>$value)
                                    <option value="{{$key}}" >{{ $value}}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->
                      
                    <div class="form-group row">
                        {{ html()->label(__('subroute::labels.backend.subroute.table.route').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('type') }}

                        <div class="col-md-10">
                            <select class="js-example-basic-multiple select2" name="routes[]" multiple="multiple">
                                @foreach($routes as $route)
                                    <option value="{{$route->id}}"  
                                    @foreach($routeIds as $id)
                                        @if($route->id == $id) selected @endif
                                    @endforeach
                                        >{{ $route->fromCity->name }} to {{ $route->toCity->name }}</option>
                                @endforeach
                            </select>
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_height').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('max_height') }}

                        <div class="col-md-10">
                            {{ html()->text('max_height')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_height'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_weight').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('max_weight') }}

                        <div class="col-md-10">
                            {{ html()->text('max_weight')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_weight'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_width').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('max_width') }}

                        <div class="col-md-10">
                            {{ html()->text('max_width')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_width'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.max_length'))->class('col-md-2 form-control-label')->for('max_length') }}

                        <div class="col-md-10">
                            {{ html()->text('max_length')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.max_length'))
                                ->attribute('maxlength', 191)
                                 }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.mmk_price').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('mmk_price') }}

                        <div class="col-md-10">
                            {{ html()->text('mmk_price')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.mmk_price'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                    {{ html()->label(__('subroute::labels.backend.subroute.table.usd_price').'<span class="text-danger">*</span>')->class('col-md-2 form-control-label')->for('usd_price') }}

                        <div class="col-md-10">
                            {{ html()->text('usd_price')
                                ->class('form-control')
                                ->placeholder(__('subroute::labels.backend.subroute.table.usd_price'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.subroute.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->{{ html()->closeModelForm() }}
@endsection

@push('after-scripts')

{{ script('assets/plugins/select2/js/select2.full.min.js')}}
{{ script("assets/plugins/select2/component/components-select2.js") }}
<script>
    $(function(){

        $(".select").select2({
            placeholder: 'Choose city',
            width: '100%'
        });
    });
</script>
@endpush

Modules/SubRoute/Resources/views/index.blade.php
@extends ('backend.layouts.app')

@section ('title', app_name() . ' | ' . __('subroute::labels.backend.subroute.management'))

@section('breadcrumb-links')
    @include('subroute::includes.breadcrumb-links')
@endsection

@push('after-styles')
    {{ style("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css") }}
@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('subroute::labels.backend.subroute.management') }} <small class="text-muted">{{ __('subroute::labels.backend.subroute.list') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('subroute::includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table id="subroute-table" class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.id') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.name') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.from_township') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.to_township') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.max_weight') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.max_height') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.max_width') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.mmk_price') }}</th>
                            <th>{{ __('subroute::labels.backend.subroute.table.usd_price') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

@push('after-scripts')
    {{ script("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js") }}
    {{ script("js/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#subroute-table').DataTable({
                serverSide: true,
                ajax: {
                    url: '{!! route("admin.subroute.get") !!}',
                    type: 'post',
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                        else swal(xhr.responseJSON.message);
                    }
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data:'name', name: 'name'},
                    {data:'to_township_id', name: 'to_township_id'},
                    {data:'from_township_id', name: 'from_township_id'},
                    {data:'max_weight', name: 'max_weight'},
                    {data:'max_height', name: 'max_height'},
                    {data:'max_width', name: 'max_width'},
                    {data:'mmk_price', name: 'mmk_price'},
                    {data:'usd_price', name: 'usd_price'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500,
                fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    load_plugins();
                }
            });
        });
    </script>
@endpush

Modules/SubRoute/Resources/views/show.blade.php
@extends ('backend.layouts.app')

@section ('title', __('subroute::labels.backend.subroute.management'))

@section('breadcrumb-links')
    @include('subroute::includes.breadcrumb-links')
@endsection

@push('after-styles')
<style>
    .route-style{
        background-color: #8bdf8b;
        padding: 7px 5px;
        border-radius: 10px;
        margin-right: 5px;
    }
</style>
@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('subroute::labels.backend.subroute.management') }}
                    <small class="text-muted">{{ __('subroute::labels.backend.subroute.show') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.name') }}</th>
                            <td>{{ $subroute->name }}</td>
                        </tr>

                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.to_township') }}</th>
                            <td>{{ $subroute->toTownship->name }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.from_township') }}</th>
                            <td>{{ $subroute->fromTownship->name }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.routes') }}</th>
                            
                            <td>
                                @foreach($subroute->route->sortByDesc('pivot.create_at') as $route)
                                <span class="route-style">
                                    {{ $route->fromCity->name }} -  {{ $route->toCity->name }}
                                </span>
                                @endforeach
                            </td>
                        </tr>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.type') }}</th>         
                            <td>{!! $deliveryType !!}</td>
                        </tr>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.max_height') }}</th>
                            <td>{{ $subroute->max_height }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.max_weight') }}</th>
                            <td>{{ $subroute->max_weight }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.max_width') }}</th>
                            <td>{{ $subroute->max_width }}</td>
                        </tr>
                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.max_length') }}</th>
                            <td>{{ $subroute->max_length }}</td>
                        </tr>

                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.mmk_price') }}</th>
                            <td>{{ $subroute->mmk_price }}</td>
                        </tr>

                        <tr>
                            <th>{{ __('subroute::labels.backend.subroute.table.usd_price') }}</th>
                            <td>{{ $subroute->usd_price }}</td>
                        </tr>

                    </tbody>
                </table>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->

    <div class="card-footer">
        <div class="row">
            <div class="col">
                <small class="float-right text-muted">
                    <strong>{{ __('subroute::labels.backend.subroute.table.created') }}:</strong> {{ $subroute->updated_at->timezone(get_user_timezone()) }} ({{ $subroute->created_at->diffForHumans() }}),
                    <strong>{{ __('subroute::labels.backend.subroute.table.last_updated') }}:</strong> {{ $subroute->created_at->timezone(get_user_timezone()) }} ({{ $subroute->updated_at->diffForHumans() }})
                </small>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-footer-->
</div><!--card-->
@endsection

@push('after-scripts')

<script>


</script>
@endpush